// apps/web/src/lib/components/theme/ThemeToggle.svelte
<script lang="ts">
	import { themeStore, type Theme } from '$lib/stores/theme';
	import { Sun, Moon, Monitor } from 'lucide-svelte';

	interface Props {
		size?: 'sm' | 'md' | 'lg';
		variant?: 'button' | 'dropdown';
		showLabel?: boolean;
		class?: string;
	}

	let {
		size = 'md',
		variant = 'button',
		showLabel = false,
		class: className = ''
	}: Props = $props();

	const $themeStore = $state(themeStore);

	const themes: { value: Theme; label: string; icon: any }[] = [
		{ value: 'light', label: 'Light', icon: Sun },
		{ value: 'dark', label: 'Dark', icon: Moon },
		{ value: 'system', label: 'System', icon: Monitor }
	];

	const sizeClasses = {
		sm: 'h-8 w-8 text-sm',
		md: 'h-10 w-10 text-base',
		lg: 'h-12 w-12 text-lg'
	};

	const iconSizes = {
		sm: 16,
		md: 20,
		lg: 24
	};

	function handleThemeChange(theme: Theme) {
		themeStore.setTheme(theme);
	}

	function getThemeIcon(theme: Theme) {
		return themes.find(t => t.value === theme)?.icon || Sun;
	}

	function getThemeLabel(theme: Theme) {
		return themes.find(t => t.value === theme)?.label || 'Light';
	}

	let dropdownOpen = $state(false);

	function toggleDropdown() {
		dropdownOpen = !dropdownOpen;
	}

	function closeDropdown() {
		dropdownOpen = false;
	}
</script>

{#if variant === 'button'}
	<button
		type="button"
		class="inline-flex items-center justify-center rounded-md border border-input bg-background hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 transition-colors {sizeClasses[size]} {className}"
		onclick={() => themeStore.toggleTheme()}
		aria-label="Toggle theme"
		title="Toggle theme (currently {getThemeLabel($themeStore.resolvedTheme)})"
	>
		{#if $themeStore.resolvedTheme === 'dark'}
			<Sun size={iconSizes[size]} />
		{:else}
			<Moon size={iconSizes[size]} />
		{/if}
		{#if showLabel}
			<span class="ml-2">
				{$themeStore.resolvedTheme === 'dark' ? 'Light' : 'Dark'}
			</span>
		{/if}
	</button>
{:else if variant === 'dropdown'}
	<div class="relative">
		<button
			type="button"
			class="inline-flex items-center justify-center rounded-md border border-input bg-background hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 transition-colors {sizeClasses[size]} {className}"
			onclick={toggleDropdown}
			aria-label="Select theme"
			aria-expanded={dropdownOpen}
			aria-haspopup="true"
		>
			{@const CurrentIcon = getThemeIcon($themeStore.theme)}
			<CurrentIcon size={iconSizes[size]} />
			{#if showLabel}
				<span class="ml-2">{getThemeLabel($themeStore.theme)}</span>
			{/if}
		</button>

		{#if dropdownOpen}
			<!-- Backdrop -->
			<div
				class="fixed inset-0 z-40"
				onclick={closeDropdown}
				onkeydown={(e) => e.key === 'Escape' && closeDropdown()}
				role="button"
				tabindex="-1"
				aria-hidden="true"
			></div>

			<!-- Dropdown menu -->
			<div
				class="absolute right-0 z-50 min-w-[8rem] overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md animate-in fade-in-0 zoom-in-95 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95"
				role="menu"
				aria-orientation="vertical"
				aria-labelledby="theme-menu"
			>
				{#each themes as theme}
					<button
						type="button"
						class="relative flex w-full cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50 transition-colors"
						onclick={() => {
							handleThemeChange(theme.value);
							closeDropdown();
						}}
						role="menuitem"
						aria-current={$themeStore.theme === theme.value ? 'true' : 'false'}
					>
						<theme.icon size={16} class="mr-2" />
						<span>{theme.label}</span>
						{#if $themeStore.theme === theme.value}
							<span class="ml-auto">
								<svg
									width="16"
									height="16"
									viewBox="0 0 24 24"
									fill="none"
									stroke="currentColor"
									stroke-width="2"
									stroke-linecap="round"
									stroke-linejoin="round"
									class="lucide lucide-check"
								>
									<path d="M20 6 9 17l-5-5" />
								</svg>
							</span>
						{/if}
					</button>
				{/each}
			</div>
		{/if}
	</div>
{/if}

<style>
	@keyframes fadeIn {
		from {
			opacity: 0;
		}
		to {
			opacity: 1;
		}
	}

	@keyframes zoomIn95 {
		from {
			opacity: 0;
			transform: scale(0.95);
		}
		to {
			opacity: 1;
			transform: scale(1);
		}
	}

	.animate-in {
		animation: fadeIn 0.15s ease-out, zoomIn95 0.15s ease-out;
	}
</style>

// apps/web/components/ui/theme-toggle.tsx
"use client";

import React from "react";
import { useTheme } from "../providers/theme-provider";

interface ThemeToggleProps {
  className?: string;
  size?: "sm" | "md" | "lg";
  variant?: "default" | "outline" | "ghost";
}

const sizeClasses = {
  sm: "h-8 w-8 text-sm",
  md: "h-10 w-10 text-base",
  lg: "h-12 w-12 text-lg",
};

const variantClasses = {
  default: "bg-bg-surface border-border-default hover:bg-bg-elevated",
  outline: "border-2 border-border-default bg-transparent hover:bg-bg-surface",
  ghost: "bg-transparent hover:bg-bg-surface",
};

const SunIcon = ({ className }: { className?: string }) => (
  <svg
    className={className}
    fill="none"
    stroke="currentColor"
    strokeWidth={2}
    viewBox="0 0 24 24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <circle cx={12} cy={12} r={5} />
    <path d="M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42" />
  </svg>
);

const MoonIcon = ({ className }: { className?: string }) => (
  <svg
    className={className}
    fill="none"
    stroke="currentColor"
    strokeWidth={2}
    viewBox="0 0 24 24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79Z" />
  </svg>
);

const SystemIcon = ({ className }: { className?: string }) => (
  <svg
    className={className}
    fill="none"
    stroke="currentColor"
    strokeWidth={2}
    viewBox="0 0 24 24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect x={2} y={3} width={20} height={14} rx={2} ry={2} />
    <path d="M8 21h8M12 17v4" />
  </svg>
);

export function ThemeToggle({
  className = "",
  size = "md",
  variant = "default",
}: ThemeToggleProps) {
  const { theme, resolvedTheme, setTheme } = useTheme();

  const handleClick = () => {
    if (theme === "light") {
      setTheme("dark");
    } else if (theme === "dark") {
      setTheme("system");
    } else {
      setTheme("light");
    }
  };

  const getIcon = () => {
    const iconSize = size === "sm" ? "w-4 h-4" : size === "lg" ? "w-6 h-6" : "w-5 h-5";

    if (theme === "system") {
      return <SystemIcon className={iconSize} />;
    } else if (resolvedTheme === "dark") {
      return <MoonIcon className={iconSize} />;
    } else {
      return <SunIcon className={iconSize} />;
    }
  };

  const getTooltipText = () => {
    if (theme === "light") return "Switch to dark theme";
    if (theme === "dark") return "Switch to system theme";
    return "Switch to light theme";
  };

  return (
    <button
      onClick={handleClick}
      title={getTooltipText()}
      aria-label={getTooltipText()}
      className={`
        relative inline-flex items-center justify-center
        rounded-lg border transition-all duration-200 ease-in-out
        focus:outline-none focus-ring
        text-text-secondary hover:text-text-primary
        ${sizeClasses[size]}
        ${variantClasses[variant]}
        ${className}
      `.trim()}
    >
      {getIcon()}

      {/* Theme indicator dot */}
      {theme === "system" && (
        <span className="absolute -bottom-1 -right-1 w-2 h-2 bg-accent rounded-full border border-bg-surface" />
      )}
    </button>
  );
}

export default ThemeToggle;
