// apps/web/components/ui/button.tsx
"use client";

import React from "react";

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "primary" | "secondary" | "ghost" | "destructive" | "ai";
  size?: "sm" | "md" | "lg";
  loading?: boolean;
  children: React.ReactNode;
}

const buttonVariants = {
  primary: `
    bg-action-primary text-neutral-0 border-transparent
    hover:bg-action-primary-hover
    active:bg-action-primary-active
    disabled:bg-neutral-200 disabled:text-neutral-400
    dark:disabled:bg-neutral-800 dark:disabled:text-neutral-600
  `,
  secondary: `
    bg-neutral-100 text-text-primary border-neutral-300
    hover:bg-neutral-200
    active:bg-neutral-300
    disabled:bg-neutral-200 disabled:text-neutral-400
    dark:bg-neutral-800 dark:text-text-primary dark:border-neutral-700
    dark:hover:bg-neutral-700
    dark:active:bg-neutral-600
    dark:disabled:bg-neutral-800 dark:disabled:text-neutral-600
  `,
  ghost: `
    bg-transparent text-action-primary border-transparent
    hover:bg-action-primary hover:bg-opacity-5
    active:bg-action-primary active:bg-opacity-10
    disabled:text-neutral-400
    dark:disabled:text-neutral-600
  `,
  destructive: `
    bg-error text-neutral-0 border-transparent
    hover:opacity-90
    active:opacity-80
    disabled:bg-neutral-200 disabled:text-neutral-400
    dark:disabled:bg-neutral-800 dark:disabled:text-neutral-600
  `,
  ai: `
    bg-bg-ai text-text-ai border-border-ai
    hover:bg-opacity-80
    active:bg-opacity-70
    disabled:bg-neutral-200 disabled:text-neutral-400
    dark:disabled:bg-neutral-800 dark:disabled:text-neutral-600
    relative overflow-hidden
    before:absolute before:inset-0 before:bg-gradient-to-r
    before:from-transparent before:via-white before:to-transparent
    before:opacity-0 hover:before:opacity-10 before:transition-opacity
  `,
};

const buttonSizes = {
  sm: "h-8 px-3 text-sm gap-1.5",
  md: "h-10 px-4 text-base gap-2",
  lg: "h-12 px-6 text-lg gap-2.5",
};

const LoadingSpinner = ({ size }: { size: "sm" | "md" | "lg" }) => {
  const spinnerSize = {
    sm: "w-3 h-3",
    md: "w-4 h-4",
    lg: "w-5 h-5",
  };

  return (
    <svg
      className={`animate-spin ${spinnerSize[size]}`}
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
    >
      <circle
        className="opacity-25"
        cx="12"
        cy="12"
        r="10"
        stroke="currentColor"
        strokeWidth="4"
      />
      <path
        className="opacity-75"
        fill="currentColor"
        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
      />
    </svg>
  );
};

export function Button({
  variant = "primary",
  size = "md",
  loading = false,
  disabled,
  children,
  className = "",
  ...props
}: ButtonProps) {
  const isDisabled = disabled || loading;

  return (
    <button
      className={`
        inline-flex items-center justify-center
        rounded-lg border font-medium
        transition-all duration-200 ease-in-out
        focus:outline-none focus-ring
        disabled:cursor-not-allowed
        ${buttonVariants[variant]}
        ${buttonSizes[size]}
        ${className}
      `.trim()}
      disabled={isDisabled}
      {...props}
    >
      {loading && <LoadingSpinner size={size} />}
      {children}
    </button>
  );
}

export default Button;

// apps/web/src/lib/components/ui/Button.svelte
<script lang="ts">
	import { twMerge } from 'tailwind-merge';
	import type { Snippet } from 'svelte';

	interface Props {
		variant?: 'primary' | 'secondary' | 'ghost' | 'destructive' | 'ai-action' | 'outline';
		size?: 'sm' | 'md' | 'lg' | 'xl' | 'icon';
		disabled?: boolean;
		loading?: boolean;
		fullWidth?: boolean;
		type?: 'button' | 'submit' | 'reset';
		class?: string;
		onclick?: () => void;
		children: Snippet;
	}

	let {
		variant = 'primary',
		size = 'md',
		disabled = false,
		loading = false,
		fullWidth = false,
		type = 'button',
		class: className = '',
		onclick,
		children
	}: Props = $props();

	const baseClasses = 'inline-flex items-center justify-center rounded-md font-medium transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 active:scale-[0.98]';

	const variants = {
		primary: 'bg-primary text-primary-foreground hover:bg-primary-hover active:bg-primary-active shadow-sm hover:shadow-md',
		secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary-hover active:bg-secondary-active border border-input shadow-sm hover:shadow-md',
		ghost: 'text-primary hover:bg-primary/10 hover:text-primary active:bg-primary/20',
		destructive: 'bg-error text-white hover:bg-error-hover active:bg-red-700 shadow-sm hover:shadow-md',
		'ai-action': 'bg-ai-highlight text-white hover:bg-ai-hover active:bg-ai-active shadow-sm hover:shadow-md ai-glow',
		outline: 'border border-input bg-background hover:bg-accent hover:text-accent-foreground shadow-sm'
	};

	const sizes = {
		sm: 'h-8 px-3 text-sm gap-2',
		md: 'h-10 px-4 text-sm gap-2',
		lg: 'h-11 px-6 text-base gap-3',
		xl: 'h-12 px-8 text-base gap-3',
		icon: 'h-10 w-10'
	};

	$: computedClasses = twMerge(
		baseClasses,
		variants[variant],
		sizes[size],
		fullWidth && 'w-full',
		loading && 'cursor-not-allowed',
		className
	);

	function handleClick() {
		if (!disabled && !loading && onclick) {
			onclick();
		}
	}
</script>

<button
	{type}
	class={computedClasses}
	disabled={disabled || loading}
	onclick={handleClick}
	aria-busy={loading}
	aria-label={loading ? 'Loading...' : undefined}
>
	{#if loading}
		<svg
			class="animate-spin h-4 w-4"
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
		>
			<circle
				class="opacity-25"
				cx="12"
				cy="12"
				r="10"
				stroke="currentColor"
				stroke-width="4"
			></circle>
			<path
				class="opacity-75"
				fill="currentColor"
				d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
			></path>
		</svg>
		{#if size !== 'icon'}
			<span>Loading...</span>
		{/if}
	{:else}
		{@render children()}
	{/if}
</button>

<style>
	/* AI action button glow effect */
	:global(.ai-glow:hover) {
		box-shadow: 0 0 20px rgba(139, 92, 246, 0.3);
	}

	/* Smooth loading animation */
	@keyframes spin {
		to {
			transform: rotate(360deg);
		}
	}

	.animate-spin {
		animation: spin 1s linear infinite;
	}

	/* Enhanced focus states for accessibility */
	button:focus-visible {
		box-shadow: 0 0 0 3px rgba(129, 140, 248, 0.35);
	}

	/* Reduced motion support */
	@media (prefers-reduced-motion: reduce) {
		button {
			transition: none !important;
		}

		.animate-spin {
			animation: none;
		}
	}
</style>
